-- 登入資料庫
CONNECT ueda/ueda@localhost/XEPDB1

CREATE TABLE ueda.VW_SPC_CHARTDATA_CHAM_PRESS (
    FAB VARCHAR2(20) NOT NULL,
    MEAN_VALUE Float DEFAULT 0,
    UPDATE_TIME DATE NOT NULL,
    PROCESSUNIT VARCHAR2(20) NOT NULL
);